{counter=0};
/[cork]/ {counter++};
/[galway]/ {counter++};
/[mayo]/ {counter++};
/[donegal]/ {counter++};
/[kerry]/ {counter++};
/[tipperary]/ {counter++};
/[clare]/ {counter++};
/[tyrone]/ {counter++};
/[antrim]/ {counter++};
/[limerick]/ {counter++};
/[roscommon]/ {counter++};
/[down]/ {counter++};
/[wexford]/ {counter++};
/[meath]/ {counter++};
/[derry]/ {counter++};
/[kilkenny]/ {counter++};
/[wicklow]/ {counter++};
/[offaly]/ {counter++};
/[cavan]/ {counter++};
/[waterford]/ {counter++};
/[westmeath]/ {counter++};
/[sligo]/ {counter++};
/[laois]/ {counter++};
/[kildare]/ {counter++};
/[fermanagh]/ {counter++};
/[leitrim]/ {counter++};
/[armagh]/ {counter++};
/[monaghan]/ {counter++};
/[longford]/ {counter++};
/[dublin]/ {counter++};
/[carlow]/ {counter++};
/[louth]/ {counter++};
counter == 31 {if (length($0) > maxlen) {maxline=$0; maxlen=length;}}
END { print maxline }
